#!/bin/bash
#skripti algus
find /var -name "*.log" 2>/dev/null -exec wc -l {} \; | sort -r -n 
#find käsk leiab failid 
#2>/dev/null -exec suunab veateated antud kausta
#sort käsk sorteerib leitud failid selle järgi, kus on kõige rohkem faili nimekirjas ridu

